spring:
  config:
    import: "application-secret.yml"

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

  application:
    name: contract
  datasource:
    url: jdbc:sqlserver://${secret.mssql.endpoint};databaseName=${secret.mssql.db};encrypt=false;trustServerCertificate=true
    username: ${secret.mssql.username}
    password: ${secret.mssql.password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
      database-platform: org.hibernate.dialect.SQLServerDialect
      hibernate:
        ddl-auto: none
      show-sql: true
  jackson:
    time-zone: Asia/Seoul

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

schedule:
  cron: "0 0/5 * * * *"
  use: true

libreoffice:
#  home: "C:\\Program Files\\LibreOffice"
  home : "${OFFICE_HOME:/opt/libreoffice25.2}"
  port : 2002

